function hMainFig = shh_create_viso_gui(mainFigurePosition)

    hMainFig = figure('Position',     mainFigurePosition, ...
                      'Color',        'white', ...
                      'Name',         'Simulation Plot Window', ...
                      'NumberTitle',  'off', ...
                      'DoubleBuffer', 'on', ...
                      'MenuBar',      'none', ...
                      'Toolbar',      'none', ...
                      'Resize',       'off', ...
                      'Visible',      'off', ...
                      'UserData',     '', ...
                      'Tag',          'mainFig');
                    % MenuBar figure none
                    % Toolbar auto none
              
              
              
              
              
              
end
%eof
